"""applicants: drive file per job posting

Revision ID: 2719dee422ec
Revises: 460be233efb2
Create Date: 2026-08-30 16:19:43.856990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2719dee422ec'
down_revision: Union[str, Sequence[str], None] = '460be233efb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('drive_file_id', sa.String(length=128), nullable=False),
    sa.Column('drive_filename', sa.String(length=255), nullable=False),
    sa.Column('drive_web_link', sa.String(length=512), nullable=True),
    sa.Column('generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_file_id', name='uq_applicant_drive_file')
    )
    op.create_index(op.f('ix_applicants_application_id'), 'applicants', ['application_id'], unique=False)
    op.create_index(op.f('ix_applicants_candidate_id'), 'applicants', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_applicants_drive_file_id'), 'applicants', ['drive_file_id'], unique=False)
    op.create_index(op.f('ix_applicants_job_id'), 'applicants', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applicants_job_id'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_drive_file_id'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_candidate_id'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_application_id'), table_name='applicants')
    op.drop_table('applicants')
    # ### end Alembic commands ###
