"""job ownership

Revision ID: 81556ec501f1
Revises: 0387592340ac
Create Date: 2026-09-14 22:52:56.803893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81556ec501f1'
down_revision: Union[str, Sequence[str], None] = '0387592340ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_jobs_created_by_id'), 'jobs', ['created_by_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_created_by_id'), table_name='jobs')
    op.drop_column('jobs', 'created_by_id')
    # ### end Alembic commands ###
